apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nexus-api
  labels:
    app: nexus-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nexus-api
  template:
    metadata:
      labels:
        app: nexus-api
    spec:
      containers:
        - name: nexus-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
