apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/UyiGodfrey/nexus-devops-platform.git
    targetRevision: main
    path: helm/nexus-api

    helm:
      releaseName: nexus-gitops

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
